
development:
  adapter: postgresql
  database: db/hattip_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/hattip_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/hattip_production
  pool: 5
  timeout: 5000
